# Generated by Django 5.0.14 on 2026-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
